using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Text;
using System.Threading;
using System.Xml.Linq;
using MauiApp100.Generators.Helpers;

namespace MauiApp100.Generators;

[Generator]
public class SkiaLayoutGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var xamlFiles = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith(".xaml") && f.Path.Contains("SkiaViews"));

        var parsed = xamlFiles.Select((file, ct) =>
        {
            var name = System.IO.Path.GetFileNameWithoutExtension(file.Path);
            var content = file.GetText(ct)?.ToString() ?? "";
            return new Model(name, content);
        });

        context.RegisterSourceOutput(parsed, (spc, model) =>
        {
            try
            {
                var xdoc = XDocument.Parse(model.Content);

                // USAMOS TU PARSER
                var root = XamlParser.Parse(xdoc.Root);

                var sb = new StringBuilder();

                //  GENERACION PLANA
                BuildDrawCode(root, sb, 0, 0, "width", "height");

                var drawCode = sb.ToString();

                var code = $@"// <auto-generated/>
using SkiaSharp;
using SkiaSharp.Views.Maui;
using SkiaSharp.Views.Maui.Controls;

namespace MauiApp100.Controls;

public partial class {model.Name}SkiaGen : ContentView
{{
    private SKCanvasView canvas;

    public dynamic Item {{ get; set; }}

    public {model.Name}SkiaGen()
    {{
        canvas = new SKCanvasView();
        canvas.PaintSurface += OnPaintSurface;
        Content = canvas;
    }}

    private void OnPaintSurface(object sender, SKPaintSurfaceEventArgs e)
    {{
        var canvas = e.Surface.Canvas;
        var info = e.Info;

        canvas.Clear(SKColors.Transparent);

        if (Item == null) return;

        var paint = new SKPaint {{ IsAntialias = true }};
        var font = new SKFont {{ Size = 20 }};

        float width = info.Width;
        float height = info.Height;

        {drawCode}
    }}
}}
";

                spc.AddSource($"{model.Name}.Skia.g.cs",
                    SourceText.From(code, Encoding.UTF8));
            }
            catch (Exception ex)
            {
                spc.AddSource($"{model.Name}.error.g.cs",
                    SourceText.From($"// ERROR: {ex}", Encoding.UTF8));
            }
        });
    }

    // =========================================
    // GENERADOR PLANO (USA TU MODELO)
    // =========================================
    static void BuildDrawCode(Node node, StringBuilder sb, float x, float y, string w, string h)
    {
        switch (node)
        {
            case StackNode s:
                {
                    int count = Math.Max(1, s.Children.Count);
                    float offset = 0;

                    for (int i = 0; i < s.Children.Count; i++)
                    {
                        var child = s.Children[i];

                        if (s.Horizontal)
                        {
                            var cw = $"{w} / {count}f";
                            BuildDrawCode(child, sb, x + offset, y, cw, h);
                            offset += 1000f / count; // solo distribución base
                        }
                        else
                        {
                            var ch = $"{h} / {count}f";
                            BuildDrawCode(child, sb, x, y + offset, w, ch);
                            offset += 200f / count;
                        }
                    }
                    break;
                }

            case GridNode g:
                {
                    int cols = Math.Max(1, g.Columns.Count);
                    int rows = Math.Max(1, g.Rows.Count);

                    string cellW = $"{w} / {cols}f";
                    string cellH = $"{h} / {rows}f";

                    foreach (var c in g.Children)
                    {
                        BuildDrawCode(
                            c,
                            sb,
                            x + c.Column * 100,
                            y + c.Row * 40,
                            cellW,
                            cellH);
                    }
                    break;
                }

            case LabelNode l:
                {
                    string textExpr = !string.IsNullOrEmpty(l.Format)
                        ? $"string.Format(\"{l.Format}\", Item.{l.Binding})"
                        : $"Item.{l.Binding}";

                    string alignOffset = l.Align switch
                    {
                        "Center" => " + 50",
                        "End" => " + 100",
                        _ => ""
                    };

                    string fontStyle = l.Bold ? "font.Embolden = true;" : "";

                    string color = $"paint.Color = SKColors.{l.Color};";

                    sb.AppendLine($@"
{color}
{fontStyle}
canvas.DrawText(
    {textExpr},
    {x}f{alignOffset},
    {y + 20}f,
    font,
    paint);");
                    break;
                }

            case ButtonNode b:
                {
                    string color = $"paint.Color = SKColors.{b.Color};";

                    sb.AppendLine($@"
{color}
canvas.DrawText(
    ""{b.Glyph}"",
    {x}f,
    {y + 20}f,
    font,
    paint);");
                    break;
                }

            default:
                foreach (var c in node.Children)
                    BuildDrawCode(c, sb, x, y, w, h);
                break;
        }
    }

    private record Model(string Name, string Content);
}