<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
        <TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net7.0-tizen</TargetFrameworks> -->
		<OutputType>Exe</OutputType>
		<RootNamespace>DMCobranzas</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>DMCobranzas</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.macronegocios.cobranzas</ApplicationId>
		<ApplicationIdGuid>5339d0ab-ec3a-4fbf-8b91-9ab60f435ad1</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<WindowsPackageType>None</WindowsPackageType>
				
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>		
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-android|AnyCPU'">
		<AndroidStoreUncompressedFileExtensions></AndroidStoreUncompressedFileExtensions>
		<ApplicationVersion>39</ApplicationVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-ios|AnyCPU'">
	  <ApplicationVersion>39</ApplicationVersion>
	  <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
	  <FileAlignment>8192</FileAlignment>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-maccatalyst|AnyCPU'">
	  <ApplicationVersion>39</ApplicationVersion>
	  <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
	  <FileAlignment>8192</FileAlignment>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows10.0.19041.0|AnyCPU'">
	  <ApplicationVersion>39</ApplicationVersion>
	  <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
	  <FileAlignment>8192</FileAlignment>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-android|AnyCPU'">
		<Optimize>True</Optimize>
		<AndroidStoreUncompressedFileExtensions></AndroidStoreUncompressedFileExtensions>
		<ApplicationVersion>39</ApplicationVersion>
		<AndroidPackageFormat>aab</AndroidPackageFormat>
		<AndroidUseAapt2>True</AndroidUseAapt2>
		<AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-ios|AnyCPU'">
	  <ApplicationVersion>39</ApplicationVersion>
	  <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
	  <FileAlignment>8192</FileAlignment>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-maccatalyst|AnyCPU'">
	  <ApplicationVersion>39</ApplicationVersion>
	  <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
	  <FileAlignment>8192</FileAlignment>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows10.0.19041.0|AnyCPU'">
	  <ApplicationVersion>39</ApplicationVersion>
	  <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
	  <FileAlignment>8192</FileAlignment>
	</PropertyGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
		<AndroidSupportedAbis>arm64-v8a;x86_64</AndroidSupportedAbis>
	</PropertyGroup>	

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4">
		  <BaseSize>256,256</BaseSize>
		</MauiIcon>

		<!-- Splash Screen -->
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#EDE6EB" BaseSize="190,90" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>	

	<ItemGroup>
	  <AndroidResource Remove="__bin\**" />
	  <AndroidResource Remove="__obj\**" />
	  <Compile Remove="__bin\**" />
	  <Compile Remove="__obj\**" />
	  <EmbeddedResource Remove="__bin\**" />
	  <EmbeddedResource Remove="__obj\**" />
	  <MauiCss Remove="__bin\**" />
	  <MauiCss Remove="__obj\**" />
	  <MauiXaml Remove="__bin\**" />
	  <MauiXaml Remove="__obj\**" />
	  <None Remove="__bin\**" />
	  <None Remove="__obj\**" />
	</ItemGroup>	

	<ItemGroup>
	  <AndroidResource Remove="Platforms\Android\Resources\drawable\maui_splash.xml" />
	  <AndroidResource Remove="Platforms\Android\Resources\values\styles.xml" />
	</ItemGroup>	

	<ItemGroup>
	  <Compile Remove="AppPages\NotaCredito\AccountMoveSendProdCrud.xaml.cs" />
	  <Compile Remove="AppPages\Printing\DeviceLocal.cs" />
	  <Compile Remove="Controls\AccountMoveInvoiceForSend.cs" />
	  <Compile Remove="Controls\AccountMoveInvoiceLineForSend.cs" />
	  <Compile Remove="Controls\CustomHeaderView.cs" />
	  <Compile Remove="Controls\InvoicePaymentItem.cs" />
	  <Compile Remove="Controls\InvoicePaymentItemV2.cs" />
	  <Compile Remove="Controls\ItemAccountMove.cs" />
	  <Compile Remove="Controls\PaymentHeaderItem.cs" />
	  <Compile Remove="Controls\PopupResPartnerBank.cs" />
	  <Compile Remove="Controls\PopupSelectBase.cs" />
	  <Compile Remove="Controls\PopupSelectInvoice.cs" />
	  <Compile Remove="Controls\PopupSelectInvoiceItems.cs" />
	  <Compile Remove="Controls\PopupSelectPartner.cs" />
	  <Compile Remove="Controls\PopupSelectPartnerBank.cs" />
	  <Compile Remove="Controls\PopupSize.cs" />
	  <Compile Remove="Controls\ProgressBarAnimationBehaviorPage.xaml.cs" />
	  <Compile Remove="Controls\ReturnResultPopup.xaml.cs" />
	  <Compile Remove="Controls\ReturnResultPopupSearch.xaml.cs" />
	  <Compile Remove="Controls\SimplePopupAutoclose.xaml.cs" />
	  <Compile Remove="Login_deprecated.xaml.cs" />
	  <Compile Remove="Models\SendController.cs" />
	  <Compile Remove="Resources\Fonts\FluentUI.cs" />
	  <Compile Remove="Services\AlertService.cs" />
	  <Compile Remove="Services\BluetoothPrinterManager.cs" />
	  <Compile Remove="Services\PrintCommandBytes.cs" />
	  <Compile Remove="Services\PrinterCommand.cs" />
	  <Compile Remove="Services\PushRelay.cs" />
	  <Compile Remove="Services\Shared\BasePrinterService.cs" />
	  <Compile Remove="Settings\Constants.cs" />
	</ItemGroup>

	<ItemGroup>
	  <MauiAsset Remove="Resources\Raw\dotliquid_test.txt" />
	  <MauiAsset Remove="Resources\Raw\liq_refund_req_ncr.txt" />
	  <MauiAsset Remove="Resources\Raw\liq_req_movSendHead_ncr.txt" />
	  <MauiAsset Remove="Resources\Raw\liq_test.txt" />
	  <MauiAsset Remove="Resources\Raw\liq_ticket_closing.txt" />
	  <MauiAsset Remove="Resources\Raw\liq_ticket_small.liquid" />
	  <MauiAsset Remove="Resources\Raw\liq_ticket_small.txt" />
	</ItemGroup>

	<ItemGroup>
	  <MauiFont Remove="Resources\Fonts\OpenSans-Semibold__old.ttf" />
	</ItemGroup>

	<ItemGroup>
	  <MauiImage Remove="Resources\Images\demo2.bmp" />
	  <MauiImage Remove="Resources\Images\logo_dmujeres.bmp" />
	  <MauiImage Remove="Resources\Images\logo_macronegocios.bmp" />
	  <MauiImage Remove="Resources\Images\logo_macronegocios_gray.bmp" />
	  <MauiImage Remove="Resources\Images\logo_neutro.bmp" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Remove="AppPages\NotaCredito\AccountMoveSendProdCrud.xaml" />
	  <MauiXaml Remove="Controls\ProgressBarAnimationBehaviorPage.xaml" />
	  <MauiXaml Remove="Controls\ReturnResultPopup.xaml" />
	  <MauiXaml Remove="Controls\ReturnResultPopupSearch.xaml" />
	  <MauiXaml Remove="Controls\SimplePopupAutoclose.xaml" />
	  <MauiXaml Remove="Login_deprecated.xaml" />
	  <MauiXaml Remove="Resources\Styles\Colors-Original.xaml" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\AppIcon\appicon.svg" />
	  <None Remove="Resources\Fonts\Consolas.ttf" />
	  <None Remove="Resources\Fonts\fa-brands-400.ttf" />
	  <None Remove="Resources\Fonts\fa-regular-400.ttf" />
	  <None Remove="Resources\Fonts\fa-solid-900.ttf" />
	  <None Remove="Resources\Fonts\Font Awesome 5 Brands-Regular-400.otf" />
	  <None Remove="Resources\Fonts\Font Awesome 5 Free-Regular-400.otf" />
	  <None Remove="Resources\Fonts\Font Awesome 5 Free-Solid-900.otf" />
	  <None Remove="Resources\Fonts\OpenSans-Semibold__old.ttf" />
	  <None Remove="Resources\Images\alert.svg" />
	  <None Remove="Resources\Images\demo2.bmp" />
	  <None Remove="Resources\Images\logo_dmujeres.svg" />
	  <None Remove="Resources\Images\logo_macronegocios.svg" />
	  <None Remove="Resources\Images\user_svgrepo_com.svg" />
	  <None Remove="Resources\Images\warning.svg" />
	  <None Remove="Resources\Raw\dotliquid_test.txt" />
	  <None Remove="Resources\Raw\liq_refund_req_ncr.txt" />
	  <None Remove="Resources\Raw\liq_req_movSendHead_ncr.txt" />
	  <None Remove="Resources\Raw\liq_test.txt" />
	  <None Remove="Resources\Raw\liq_ticket_closing.txt" />
	  <None Remove="Resources\Raw\liq_ticket_small.liquid" />
	  <None Remove="Resources\Raw\liq_ticket_small.txt" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Resources\Images\demo2.bmp" />
	  <EmbeddedResource Include="Resources\Images\logo_dmujeres.bmp" />
	  <EmbeddedResource Include="Resources\Images\logo_macronegocios.bmp" />
	  <EmbeddedResource Include="Resources\Images\logo_macronegocios_gray.bmp" />
	  <EmbeddedResource Include="Resources\Images\logo_neutro.bmp" />
	  <EmbeddedResource Include="Resources\Raw\liq_req_movSendHead_ncr.txt" />
	  <EmbeddedResource Include="Resources\Raw\liq_refund_req_ncr.txt" />
	  <EmbeddedResource Include="Resources\Raw\liq_ticket_closing.txt" />
	  <EmbeddedResource Include="Resources\Raw\liq_test.txt" />
	  <EmbeddedResource Include="Resources\Raw\liq_ticket_small.liquid" />
	  <EmbeddedResource Include="Resources\Raw\excluded\liq_ticket_small.txt" />
	  <EmbeddedResource Include="Resources\Raw\dotliquid_test.txt" />
	</ItemGroup>

	<ItemGroup>
        <PackageReference Include="CommunityToolkit.Maui" Version="14.1.0" />
        <PackageReference Include="CommunityToolkit.Maui.Core" Version="14.1.0" />
        <PackageReference Include="CommunityToolkit.Maui.Markup" Version="7.0.1" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Fluid.Core" Version="2.31.0" />
		<PackageReference Include="Microsoft.AppCenter" Version="5.0.7" />
		<PackageReference Include="Microsoft.AppCenter.Analytics" Version="5.0.7" />
		<PackageReference Include="Microsoft.AppCenter.Crashes" Version="5.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.6" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="RestSharp" Version="114.0.0" />
		<PackageReference Include="SkiaSharp" Version="3.119.2" />
		<PackageReference Include="SkiaSharp.QrCode" Version="0.12.0" />		
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ApiManagerOdoo\ApiManagerOdoo.csproj" />
	  <ProjectReference Include="..\BeebTech.Controls\BeebTech.Controls.csproj" />	  
	  <ProjectReference Include="..\BeebTech.Maui.Controls\BeebTech.Maui.Controls.csproj" />
	  <ProjectReference Include="..\DMSA.Models.Odoo\DMSA.Models.Odoo.csproj" />
	  <ProjectReference Include="..\DMSA.Sync.Core\DMSA.Sync.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="AppPages\AppFlyout.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="AppPages\Cobranzas\CobranzasPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="AppPages\Cobranzas\AccountPaymentCrud.xaml.cs">
	    <DependentUpon>AccountPaymentCrud.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="AppPages\Cobranzas\AccountPaymentView.xaml.cs">
	    <DependentUpon>AccountPaymentView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="AppPages\FlyoutMenuPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="AppPages\NotaCredito\CreditNoteRequestGroupView.xaml.cs">
	    <DependentUpon>CreditNoteRequestGroupView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="AppPages\NotaCredito\CreditNoteRequestCrud.xaml.cs">
	    <DependentUpon>CreditNoteRequestCrud.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="AppPages\NotaCredito\NotasCreditoPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="AppPages\Printing\TestTool.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="AppPages\Printing\PrintView.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="AppPages\Sys\About.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="AppPages\Sys\SettingsPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="AppPages\UpdateData.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Controls\CustomListItem.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Controls\CustomRows\MultipleCobrosInvoiceLineAiRow.xaml.cs">
	    <DependentUpon>MultipleCobrosInvoiceLineAiRow.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Controls\CustomRows\MultipleCobrosInvoiceRow.xaml.cs">
	    <DependentUpon>MultipleCobrosInvoiceRow.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Controls\PopupLoadingTask.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="DetailModal.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="MainPage.xaml.cs">
	    <SubType>Code</SubType>
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="AppPages\AppFlyout.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="AppPages\Cobranzas\CobranzasPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="AppPages\Cobranzas\AccountPaymentCrud.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="AppPages\Cobranzas\AccountPaymentView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="AppPages\FlyoutMenuPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="AppPages\NotaCredito\CreditNoteRequestGroupView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="AppPages\NotaCredito\CreditNoteRequestCrud.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="AppPages\NotaCredito\NotasCreditoPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="AppPages\Printing\TestTool.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="AppPages\Printing\PrintView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="AppPages\Sys\About.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="AppPages\Sys\Connections.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="AppPages\Sys\SettingsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="AppPages\UpdateData.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomListItem.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomPicker.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomPickerPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\CreditNoteRequestDetailRow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\CreditNoteRequestGroupRow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\CustomHeaderView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\MultipleCobrosInvoiceLineAiRow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\MultipleCobrosInvoiceRow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\PopupLoadingTask.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\ProgressBarPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="DetailModal.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Login.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
        <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.51" />
        <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.51" />		
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Services\Shared\" />
	</ItemGroup>

</Project>
