<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
        <TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>
		
		<OutputType>Exe</OutputType>
		<RootNamespace>DMOrders</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>		
		
		<ApplicationTitle Condition="'$(Configuration)' == 'Debug'">DMOrders</ApplicationTitle>
		<ApplicationTitle Condition="'$(Configuration)' == 'Release'">DMOrders</ApplicationTitle>
		
		<!-- App Identifier -->
		<ApplicationId>com.macronegocios.orders</ApplicationId>
		<ApplicationIdGuid>ad97729f-51ee-4af9-8f3b-3a3b338c3e04</ApplicationIdGuid>
		
		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>
		<WindowsPackageType>None</WindowsPackageType>
		
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
		<Configurations>Debug;Release</Configurations>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-android|AnyCPU'">
	  <Optimize>True</Optimize>
	  <AndroidStoreUncompressedFileExtensions></AndroidStoreUncompressedFileExtensions>
	  <ApplicationVersion>33</ApplicationVersion>
	  <AndroidPackageFormat>aab</AndroidPackageFormat>
	  <AndroidUseAapt2>True</AndroidUseAapt2>
	  <AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
		<RunAOTCompilation>False</RunAOTCompilation>	  
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-ios|AnyCPU'">
	  <Optimize>True</Optimize>
	  <ApplicationVersion>33</ApplicationVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-maccatalyst|AnyCPU'">
	  <Optimize>True</Optimize>
	  <ApplicationVersion>33</ApplicationVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows10.0.19041.0|AnyCPU'">
	  <Optimize>True</Optimize>
	  <ApplicationVersion>33</ApplicationVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-android|AnyCPU'">
	  <AndroidStoreUncompressedFileExtensions></AndroidStoreUncompressedFileExtensions>
	  <ApplicationVersion>33</ApplicationVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-ios|AnyCPU'">
	  <ApplicationVersion>33</ApplicationVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-maccatalyst|AnyCPU'">
	  <ApplicationVersion>33</ApplicationVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows10.0.19041.0|AnyCPU'">
	  <ApplicationVersion>33</ApplicationVersion>
	</PropertyGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
		<AndroidSupportedAbis>armeabi-v7a;x86;arm64-v8a;x86_64</AndroidSupportedAbis>
		<AndroidCreatePackagePerAbi>false</AndroidCreatePackagePerAbi>
	</PropertyGroup>

	<!--<PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
		<AndroidSupportedAbis>armeabi-v7a;x86;x86_64;arm64-v8a</AndroidSupportedAbis>
	</PropertyGroup>-->

	<!--<PropertyGroup>
		<RuntimeIdentifiers Condition="$(TargetFramework.Contains('-android'))">android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
	</PropertyGroup>-->

	<!--<PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
		<RuntimeIdentifiers>android-arm64</RuntimeIdentifiers>
	</PropertyGroup>-->

	<ItemGroup>

		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#52D681" />
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#EDE6EB" BaseSize="272,153" />
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		<MauiFont Include="Resources\Fonts\*" CopyToOutputDirectory="Always" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>	

	<ItemGroup>
	  <AndroidResource Remove="Services\Update\**" />
	  <Compile Remove="Services\Update\**" />
	  <EmbeddedResource Remove="Services\Update\**" />
	  <MauiCss Remove="Services\Update\**" />
	  <MauiXaml Remove="Services\Update\**" />
	  <None Remove="Services\Update\**" />
	</ItemGroup>	

	<ItemGroup>
	  <AndroidResource Remove="Platforms\Android\Resources\drawable\maui_splash.xml" />
	  <AndroidResource Remove="Platforms\Android\Resources\values\styles.xml" />
	</ItemGroup>	

	<ItemGroup>
	  <Compile Remove="Controls\Base\Row.cs" />
	  <Compile Remove="Controls\Base\RowAdvance.cs" />
	  <Compile Remove="Controls\CustomRows\AccountAnalyticLineRow.cs" />
	  <Compile Remove="Controls\CustomRows\ActivityRow.cs" />
	  <Compile Remove="Controls\CustomRows\BaseCell.cs" />
	  <Compile Remove="Controls\CustomRows\BaseRow.cs" />
	  <Compile Remove="Controls\CustomRows\BrandRow.cs" />
	  <Compile Remove="Controls\CustomRows\MarcaRow.cs" />
	  <Compile Remove="Controls\CustomRows\PlanningSlotRow.cs" />
	  <Compile Remove="Controls\CustomRows\ProductCanvasRow.cs" />
	  <Compile Remove="Controls\CustomRows\ProductCategoryRow.cs" />
	  <Compile Remove="Controls\CustomRows\ProductExtraRow.cs" />
	  <Compile Remove="Controls\CustomRows\ProductRow.cs" />
	  <Compile Remove="Controls\CustomRows\ProductViewerRow.cs" />
	  <Compile Remove="Controls\CustomRows\ResPartnerRow.cs" />
	  <Compile Remove="Controls\CustomRows\SaleOrderLineRow.cs" />
	  <Compile Remove="Controls\CustomRows\SaleOrderRow.cs" />
	  <Compile Remove="Controls\PopupSelectBrand.cs" />
	  <Compile Remove="Pages\Fragments\Customers\PartnerItemViewModel.cs" />
	  <Compile Remove="Pages\Fragments\Orders\CrudViewModel.cs" />
	  <Compile Remove="Pages\Fragments\Orders\modals\bk\PromocionesViewer.xaml.cs" />
	  <Compile Remove="Pages\Fragments\Orders\modals\CatalogViewer.xaml.cs" />
	  <Compile Remove="Pages\Fragments\Orders\modals\CatalogViewerModel.cs" />
	  <Compile Remove="Pages\Fragments\Product\Details.xaml.cs" />
	  <Compile Remove="Pages\Fragments\Product\DetailsViewModel.cs" />
	  <Compile Remove="Pages\Sys\ConnectionForm.xaml.cs" />
	  <Compile Remove="Pages\Sys\UpdateData.xaml.Static.cs" />
	  <Compile Remove="Services\Promotions\bk\PromotionEngineLite.cs" />
	  <Compile Remove="Services\Promotions\bk\PromotionEngineLite.Fixed.cs" />
	</ItemGroup>
	

	<ItemGroup>
	  <MauiXaml Remove="Pages\Fragments\Orders\modals\CatalogViewer.xaml" />
	  <MauiXaml Remove="Pages\Fragments\Product\Details.xaml" />
	  <MauiXaml Remove="Pages\Sys\ConnectionForm.xaml" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Platforms\Android\env.conf" />
		<None Remove="Resources\AppIcon\appicon.svg" />
		<None Remove="Resources\Fonts\Consolas.ttf" />
		<None Remove="Resources\Fonts\fa-brands-400.ttf" />
		<None Remove="Resources\Fonts\fa-regular-400.ttf" />
		<None Remove="Resources\Fonts\fa-solid-900.ttf" />
		<None Remove="Resources\Fonts\Font Awesome 5 Brands-Regular-400.otf" />
		<None Remove="Resources\Fonts\Font Awesome 5 Free-Regular-400.otf" />
		<None Remove="Resources\Fonts\Font Awesome 5 Free-Solid-900.otf" />		
	</ItemGroup>

	<ItemGroup>
	  <AndroidEnvironment Include="Platforms\Android\env.conf" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Include="Services\Update\LaunchManager.cs" />
	</ItemGroup>

	<ItemGroup>		
        <PackageReference Include="CommunityToolkit.Maui" Version="14.1.0" />
        <PackageReference Include="CommunityToolkit.Maui.Core" Version="14.1.0" />
        <PackageReference Include="CommunityToolkit.Maui.Markup" Version="7.0.1" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.7" />
        <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.51" />
        <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.51" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.7" />
        <PackageReference Include="Microsoft.Maui.Graphics" Version="10.0.51" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.7" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.7" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
		
		<PackageReference Include="M.BindableProperty.Generator" Version="0.11.1" />
		
		<PackageReference Include="MPowerKit.VirtualizeListView" Version="2.8.0" />
		
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="RestSharp" Version="114.0.0" />

		<PackageReference Include="Plugin.BLE" Version="3.2.0" />
		<PackageReference Include="SkiaSharp" Version="3.119.2" />
		<PackageReference Include="SkiaSharp.QrCode" Version="0.12.0" />
		<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="3.119.2" />
		<PackageReference Include="SkiaSharp.Views.Maui.Core" Version="3.119.2" />
		<PackageReference Include="Spinner.MAUI" Version="1.1.2" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.7" />
		<PackageReference Include="UraniumUI" Version="2.15.0" />
		<PackageReference Include="UraniumUI.Blurs" Version="2.15.0" />
		<PackageReference Include="UraniumUI.Dialogs.CommunityToolkit" Version="2.15.0" />
		<PackageReference Include="UraniumUI.Dialogs.Mopups" Version="2.15.0" />
		<PackageReference Include="UraniumUI.Icons.FontAwesome" Version="2.15.0" />
		<PackageReference Include="UraniumUI.Icons.MaterialIcons" Version="2.15.0" />
		<PackageReference Include="UraniumUI.Icons.MaterialSymbols" Version="2.15.0" />
		<PackageReference Include="UraniumUI.Icons.SegoeFluent" Version="2.15.0" />
		<PackageReference Include="UraniumUI.Material" Version="2.15.0" />
		<PackageReference Include="UraniumUI.Validations.DataAnnotations" Version="2.15.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ApiManagerOdoo\ApiManagerOdoo.csproj" />
	  <ProjectReference Include="..\BeebTech.Maui.Controls\BeebTech.Maui.Controls.csproj" />
	  <ProjectReference Include="..\DMSA.Models.Odoo\DMSA.Models.Odoo.csproj" />
	  <ProjectReference Include="..\DMSA.Sync.Core\DMSA.Sync.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Controls\Popups\AccountAnalyticLineView.xaml.cs">
	    <DependentUpon>AccountAnalyticLineView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\Fragments\Orders\Crud.xaml.cs">
	    <DependentUpon>Crud.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Controls\Alerts\OptionPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\ConfettiOverlay.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\Lite\SaleOrderLineRow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\Lite\AccountAnalyticLineRow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\Lite\ActivityRow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\Lite\MarcaRow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\Lite\ProductCanvasRow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\Lite\ProductCategoryRow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\Lite\ProductViewerRow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\Lite\ResPartner.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\Lite\ResPartnerSingle.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\CustomRows\Lite\SaleOrderRow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\PopupLoadingTask.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\Popups\AccountAnalyticLineView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\ProgressBarPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Login.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MainPageTab.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Base\Sion\MiniMemoryGame.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\FilterCustomer.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Activities\Container.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Activities\DataGrid.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Activities\Details.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Activities\Filters.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Customers\Container.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Customers\DataGrid.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Customers\Filters.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Customers\Info.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Customers\PagingFragment.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Orders\Container.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Orders\DataGrid.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Orders\Crud.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Orders\Filters.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Orders\modals\CatalogViewerInner.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Orders\modals\PromocionesViewer.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Product\Container.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Product\DataGrid.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Product\Filters.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Fragments\Product\Info.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\PagingFragment.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Sys\About.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Sys\Connections.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Sys\SettingsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Sys\UpdateData.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\classic\Colors.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\classic\Styles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>	  
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Pages\Fragments\Orders\modals\bk\" />
	  <Folder Include="Services\Promotions\bk\" />
	  <Folder Include="ViewModels\DataGrid\" />
	</ItemGroup>
</Project>
