using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Text;
using System.Threading;

namespace MauiApp100.Generators;

[Generator]
public class SkiaLayoutGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var xamlFiles = context.AdditionalTextsProvider
            .Where(file =>
                file.Path.EndsWith(".xaml", StringComparison.OrdinalIgnoreCase) &&
                file.Path.Contains("SkiaViews"));

        var parsed = xamlFiles.Select((AdditionalText file, CancellationToken ct) =>
        {
            var name = System.IO.Path.GetFileNameWithoutExtension(file.Path);
            var content = file.GetText(ct)?.ToString() ?? "";
            return new Model(name, content);
        });

        context.RegisterSourceOutput(parsed, (spc, model) =>
        {
            string namespaceClase = "MauiApp100.Controls.SkiaViews";
            int classIndex = model.Content.IndexOf("x:Class=\"");
            if (classIndex != -1)
            {
                int start = classIndex + "x:Class=\"".Length;
                int end = model.Content.IndexOf("\"", start);
                if (end != -1)
                {
                    var fullPath = model.Content.Substring(start, end - start);
                    int lastDot = fullPath.LastIndexOf('.');
                    if (lastDot != -1) namespaceClase = fullPath.Substring(0, lastDot);
                }
            }

            bool esSkiaLayout = model.Content.Contains("Skia");

            var code = $@"// <auto-generated/>
namespace {namespaceClase};

public partial class {model.Name}
{{
    public bool EsConfiguracionSkiaValida => {esSkiaLayout.ToString().ToLower()};

    public void InicializarComponentesSkia()
    {{
        // Codigo generado dinamicamente
    }}
}}";

            spc.AddSource($"{model.Name}.g.cs", SourceText.From(code, Encoding.UTF8));
        });
    }

    private record Model(string Name, string Content);
}