<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DMSA.Models.Odoo\DMSA.Models.Odoo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Backup\" />
    <Folder Include="eliminar\" />
  </ItemGroup>

</Project>
