<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFrameworks>
		  net9.0-android;
		  net9.0-ios;
		  net9.0-maccatalyst;
		  net9.0-windows10.0.19041.0
	  </TargetFrameworks>

	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseMaui>true</UseMaui>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Controls\NativeDropdown\**" />
    <EmbeddedResource Remove="Controls\NativeDropdown\**" />
    <MauiCss Remove="Controls\NativeDropdown\**" />
    <MauiXaml Remove="Controls\NativeDropdown\**" />
    <None Remove="Controls\NativeDropdown\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Maui" Version="9.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
    <PackageReference Include="Microsoft.Maui.Graphics" Version="9.0.120" />
	  
  </ItemGroup>
  <ItemGroup>
    <MauiXaml Update="CheckBoxEx.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Controls\DropdownMenu.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Controls\TitledEntry.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Controls\TitledPicker.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.120" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.120" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\TitledEntry.xaml.cs">
      <DependentUpon>TitledEntry.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
		<DefineConstants>WINDOWS;$(DefineConstants)</DefineConstants>
	</PropertyGroup>
</Project>